apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 9d6ddd28-e93e-418e-92a9-9656b6fe787b
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-experience-time
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/experience_time
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/experience_time
